kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      force_tag: true
      username:
        from_secret: docker_user
      password:
        from_secret: docker_password
      repo: registry.mightyhub.net/hnfront/hnws
      registry: registry.mightyhub.net

---
kind: pipeline
type: exec
name: deploy

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: deploy
    environment:
      docker_user:
        from_secret: docker_user
      docker_pass:
        from_secret: docker_password
    commands:
      - docker stop hnws || true && docker rm hnws || true
      - docker login --username $${docker_user} --password $${docker_pass} registry.mightyhub.net
      - docker run -d --pull=always --name hnws -p 3000:3000 registry.mightyhub.net/hnfront/hnws:1

depends_on:
  - build
